export const GALLERY_LIST_LOADING = 'GALLERY_LIST_LOADING';

export const GALLERY_LIST_SUCCESS = 'GALLERY_LIST_SUCCESS';

export const GALLERY_LIST_ERROR = 'GALLERY_LIST_ERROR';

export const CLEAR_GALLERY_LIST = 'CLEAR_GALLERY_LIST';